services:
  - type: web
    name: device-dashboard-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://https://wxwbbb.onrender.com/api
